[tasks.dev]
run_task = { name = [
    "client_dev",
    "server_dev"
], parallel = true }

[tasks.client_dev]
script = [
    "cd client",
    "yarn dev"
]

[tasks.server_dev]
script = [
    "cd server",
    "cargo run"
]